/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Vista.EditWindow;
import Modelos.Contact;

/**
 *
 * @author Usuario
 */
public class Estudiantes extends javax.swing.JPanel {
    Contact contactoEstudiantes = new Contact();
    DefaultTableModel modelo=new DefaultTableModel();
    
    
   
    public void cargarDatosEstudiantes(){
    
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Dirección");
        modelo.addColumn("Barrio");
        modelo.addColumn("Ciudad");
        modelo.addColumn("Numero");
        modelo.addColumn("Tipo");
        modelo.addColumn("Estamento");
        modelo.addColumn("Dia");
        modelo.addColumn("Mes");
        modelo.addColumn("Año");
        tablaDatosEstudiantes.setModel(modelo);
        
        ArrayList<Object[]>estudiantes=new ArrayList<Object[]>();
        
        
        for (Object []informacion : estudiantes){
            modelo.addRow(informacion);
        }
        
        tablaDatosEstudiantes.setModel(modelo);
    }

    /**
     * Creates new form Estudiantes
     */
    public Estudiantes() {
        initComponents();
        cargarDatosEstudiantes();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatosEstudiantes = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(660, 314));

        tablaDatosEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDatosEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatosEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDatosEstudiantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaDatosEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosEstudiantesMouseClicked
        // TODO add your handling code here:
        int seleccionar=tablaDatosEstudiantes.rowAtPoint(evt.getPoint());
        //EditWindow editWindow = new EditWindow();
        
        contactoEstudiantes.setNombre(String.valueOf(tablaDatosEstudiantes.getValueAt(seleccionar,1)));
        //contacto.setApellidos(String.valueOf(tabladatosProfesores.getValueAt(seleccionar,2)));
        
        String nombreContacto = contactoEstudiantes.getNombre();
        //String apellidosContacto = contacto.getApellidos();
        
        System.out.println("Nombre: " + nombreContacto);
        //System.out.println("Apellidos: " + apellidosContacto);
        
    }//GEN-LAST:event_tablaDatosEstudiantesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatosEstudiantes;
    // End of variables declaration//GEN-END:variables
}
