
package Vista;

import Modelos.ContactsList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import Modelos.ContactsList;



public class Profesores extends javax.swing.JPanel {

    public void mostrarContactos(ContactsList contactsList) {
      
        // Agregar algunos datos de prueba
        contactsList.agregarContacto("Profesor 1");
        contactsList.agregarContacto("Profesor 2");
        contactsList.agregarContacto("Profesor 3");
        
        // Obtener la lista de contactos y mostrarla en tu JPanel
        List<String> contactos = contactsList.getContactos();
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        
        // Agregar los contactos al modelo de lista
        for (String contacto : contactos) {
            listModel.addElement(contacto);
        }
        
        // Crear un JList con el modelo de lista
        JList<String> contactosJList = new JList<>(listModel);

        // Agregar el JList al panel
        add(new JScrollPane(contactosJList));
        
        // Actualizar la vista
        revalidate();
        repaint();
        
        
        for (String contacto : contactos) {
            System.out.println(contacto);
        }
    }
    
    public Profesores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setForeground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
