
package Vista;


import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import Vista.EditWindow;
import Modelos.ContactsList;

public class Profesores extends javax.swing.JPanel {
    
    ContactsList contacto = new ContactsList();
    DefaultTableModel modelo=new DefaultTableModel();
    
    
   
    public void cargardatosProfesores(){
    
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Dirección");
        modelo.addColumn("Barrio");
        modelo.addColumn("Ciudad");
        modelo.addColumn("Numero");
        modelo.addColumn("Tipo");
        modelo.addColumn("Estamento");
        modelo.addColumn("Dia");
        modelo.addColumn("Mes");
        modelo.addColumn("Año");
        tabladatosProfesores.setModel(modelo);
        
        ArrayList<Object[]>info=new ArrayList<Object[]>();
        
        
        Object[]dato1=new Object[]{"0","Juan","Duque","Cra 3","El diamante","Cali","0000000000","Movil","Estudiante","10","7","2002"};
        Object[]dato2=new Object[]{"1","Alejandro","Ceron","Cra 4","Vergel","Pasto","33333333333","Movil","Trabajador","9","3","2004"};
        Object[]dato3=new Object[]{"2","Charlotte","Garcia","Cra 1","Caney","Medellin","2222222","Telefono","Profesor","2","6","2003"};
        Object[]dato4=new Object[]{"3","Natalia","Silva","Cra 2","Poblado","Cali","1111111111","Movil","Estudiante","8","12","2005"};

        info.add(dato1);
        info.add(dato2);
        info.add(dato3);
        info.add(dato4);
        
        for (Object []informacion : info){
            modelo.addRow(informacion);
        }
        
        tabladatosProfesores.setModel(modelo);
    }

    public Profesores() {
        initComponents();
        cargardatosProfesores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatosProfesores = new javax.swing.JTable();

        setForeground(new java.awt.Color(255, 204, 255));

        tabladatosProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabladatosProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosProfesoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabladatosProfesores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabladatosProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosProfesoresMouseClicked
        // TODO add your handling code here:
        int seleccionar=tabladatosProfesores.rowAtPoint(evt.getPoint());
        //EditWindow editWindow = new EditWindow();
        
        contacto.setNombre(String.valueOf(tabladatosProfesores.getValueAt(seleccionar,1)));
        //contacto.setApellidos(String.valueOf(tabladatosProfesores.getValueAt(seleccionar,2)));
        
        String nombreContacto = contacto.getNombre();
        //String apellidosContacto = contacto.getApellidos();
        
        System.out.println("Nombre: " + nombreContacto);
        //System.out.println("Apellidos: " + apellidosContacto);
        
        /*
        EditWindow.EditID.setText(String.valueOf(tabladatosProfesores.getValueAt(seleccionar,0)));
        EditWindow.EditNombre.setText(String.valueOf(tabladatosProfesores.getValueAt(seleccionar,1)));
        EditWindow.EditApellidos.setText(String.valueOf(tabladatosProfesores.getValueAt(seleccionar,2)));
        EditWindow.EditDireccion.setText(String.valueOf(tabladatosProfesores.getValueAt(seleccionar,3)));

        */
    }//GEN-LAST:event_tabladatosProfesoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabladatosProfesores;
    // End of variables declaration//GEN-END:variables
}
